name: hornet_node
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^2.2.0
  bloc: ^7.0.0
  envify: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_hooks: ^0.17.0
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  hive_generator: ^1.1.0
  http: ^0.13.3
  injectable: ^1.4.0
  intl: ^0.17.0
  json_serializable: ^4.1.2
  retrofit: ^2.0.0-beta3
  formz: ^0.4.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator:
    git:
      url: https://github.com/trevorwang/retrofit.dart.git
      path: generator
      ref: master
  auto_route_generator: ^2.1.0
  bloc_test: ^8.0.0
  build_runner: null
  envify_generator: ^2.0.0
  freezed: ^0.14.2
  injectable_generator: ^1.4.0
  mocktail: ^0.1.2
  very_good_analysis: ^2.0.3

dependency_overrides:
  retrofit:
    git:
      url: https://github.com/trevorwang/retrofit.dart.git
      path: annotation
      ref: master

flutter:
  uses-material-design: true
  generate: true
